### ISSUE TITLE
4.22.1

### ISSUE THREAD

**Issue by uran** [RVillani/UE4Duino#10]
Hello, Rodrigo!
Thanks a lot! 
But, project with ue4Duino plugin 4.22.0 does not open in UE 4.22.1 (
Plugin rebuild result is:
   [1/2] Module.UE4Duino.cpp
    D:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(2482): error C2338: Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined.
    [2/2] Module.UE4Duino.gen.cpp
    D:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(2482): error C2338: Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined.
Took 7.2380772s to run UnrealBuildTool.exe, ExitCode=5
ERROR: UnrealBuildTool failed. See log for more details. (C:\Users\uran\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+UE_4.22\UBT-UE4Game-Win32-Development.txt)
       (see C:\Users\uran\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+UE_4.22\Log.txt for full exception trace)
AutomationTool exiting with ExitCode=5 (5)
BUILD FAILED (((((((
BUT! Rebuild with error plugin worked now! ))))))

**Comment by RVillani** [comment]
Sorry I took so long to learn about Issues on Github. I've never really explored the site. :/
I'll close this because there're already released binaries and code for UE 4.22 up to 4.24
