### ISSUE TITLE
plug in not working in versions: 4.22.2 and 4.21.2 

### ISSUE THREAD

**Issue by varlanoff** [RVillani/UE4Duino#11]
Hi Rodrigo
is an amzing plug in
i'm having an issue with the version of the plug in for the versions of unreal 4.22.2 or 4.21.2.
in the past I used succesfully the plugin in version 4.19 but now I'm trying to open the old files or create new projects with the plug in and the sistem shows me this message:
the following modules are missing or build with a different engine version : 
UE4Duino
and them the engine ask for rebuild and a new message appear that I need rebuild from the source manually.

is the same problem if I try to create a new project an install the plug in.
is a way to  update the plug in  that works with unreal version 4.22.2?

thanks

**Comment by Stufj** [comment]
Hey
We have the same issue with 4.22.2 .
Are you planing to update the plugin to 4.22.2 anytime soon?
Any help is highly appreciated.

Thank you!

**Comment by jeslaspravin** [comment]
Please provide more information on this ,For me it is working fine on version 4.22.2

**Comment by SB01inB** [comment]
I have the same problem with 4.22.2, I have downlaoded the latest version and installed it in a Plugins folder within the project. As soon as I open the project the folowing error appears:
![Unbenannt](https://user-images.githubusercontent.com/51791004/59439111-f268c580-8df4-11e9-9d65-1dc1bfc7116f.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/51791004/59439120-f85ea680-8df4-11e9-9996-88186b446a2a.PNG)

and this is my UE4Duino.uplugin file:
![Unbenannt3](https://user-images.githubusercontent.com/51791004/59439122-fac10080-8df4-11e9-8e0b-0206092c2bb7.PNG)

thanks for the help in advance!!!

**Comment by jeslaspravin** [comment]
Did you tried building it. If you see any build failed error please provide log with the error.

**Comment by SB01inB** [comment]
if I say "yes" to the rebuild: this shows up and after "ok" it will close everything. 
![Unbenannt4](https://user-images.githubusercontent.com/51791004/59444028-6d35de80-8dfd-11e9-9dd4-d2362c67647b.PNG)

**Comment by GraemePatterson** [comment]
not working with 4.22.3

**Comment by johannesschrimpf** [comment]
Same problem here, also with 4.22.3. It tells us that it needs recompiling, but automatic compilation fails and we are asked to compile it manually.

I'm not 100% sure how to do that, but right click on the UE4 project, generating a vscode project, and then building that project did not help.

**Comment by GraemePatterson** [comment]
I updated visual studio 2017 and got a successful rebuild. working now

**Comment by RVillani** [comment]
Sorry it tooke me so long to learn about Issues on Github, guys. I've never explored the site too much :/
Anyways, I'm closing this now because there are released code and binaries up to UE 4.24 by now.
