### ISSUE TITLE
Problems loading plugin in UE4duino

### ISSUE THREAD

**Issue by danielRamon** [RVillani/UE4Duino#13]
Good, I am trying to use the plugin as you say in the git but although I get to read it in UE4 when I say to activate it it does not allow me to access the project. A sign tells me that it cannot be loaded. I have poked with version 4.23 and 4.24 in both I have the same error.

I want to use the plugin because it seems interesting, but I can't. Im using it from spain but i think this is not a problem.

**Comment by RVillani** [comment]
Spain is not a problem :)
Are you trying to use it in a code project or Blueprint only project?
If it's Blueprint only, you need the plugin files with the compiled binaries. Source code only won't do it.
Check the [Releases](https://github.com/RVillani/UE4Duino/releases) zip files for versions with binaries for your UE version.

**Comment by Airudibas** [comment]
Lo siento, ya está solucionado. Solo tenía que instalar visual studio
community.

**Comment by RVillani** [comment]
No problem. Glad you solved it :)
I'm closing this issue, then.
