### ISSUE TITLE
I've installed 4.24.2 and 24.1 U4DUINO

### ISSUE THREAD

**Issue by gmndw6** [RVillani/UE4Duino#15]
![image](https://user-images.githubusercontent.com/50259660/74673923-32394580-51eb-11ea-821d-38b099791a02.png)

**Comment by TheSandymanCan** [comment]
I'm having the same error. Is there something we're doing wrong?

**Comment by gmndw6** [comment]
![image](https://user-images.githubusercontent.com/50259660/74999007-561fb400-5495-11ea-9abd-3446f337a501.png)
![image](https://user-images.githubusercontent.com/50259660/74999034-751e4600-5495-11ea-9039-bdb0916252bd.png)

**Comment by gmndw6** [comment]
It's working fine now
