### ISSUE TITLE
Problem Loading Ue4Duino

### ISSUE THREAD

**Issue by johnpaullima** [RVillani/UE4Duino#16]
I´m having trouble running UE4Duino. I created a new project and put ue4Duino (correct version) inside Plugins Folder. When I try to open the project it says "failed to load plugin ue4duino because module could not loaded" And the project closes. I tried with version 4.23.1 and also 4.24.1 (I downloaded the two engine versions).
![image](https://user-images.githubusercontent.com/45721283/76121167-d552d300-5fd1-11ea-925e-736ea84319d9.png)

**Comment by johnpaullima** [comment]
I managed to solve it. If someone is experiencing the same, try this:
1. Check if Visual Studio is installed with "game development with C++".
2. Create a blank project with C++ and not Blueprint
3. Create Plugins Folder and put inside all ue4duino files without Binaries folder (delete it).
4. Wait the project load and select rebuild plugin.
5. After that, copy this ue4duino folder with your recompiled binaries to whatever project you want, including VR templates using only blueprints.
that is it!

**Comment by JasonSchneider** [comment]
I just wanted to add that I ran into this same issue and this worked for me.
