### ISSUE TITLE
Plugin failed to create packaged build, UE 4.17.2

### ISSUE THREAD

**Issue by DarkenedGit** [RVillani/UE4Duino#3]
Can not create a packed build for any of the types, Windows, WindowsNoEditor, WindowsClient, WindowsServer. Get the following issue even though the plugin does appear to be enabled correctly in the editor.  Project is Blueprint only, not sure if I have to build something to get it included properly for non C++ projects.

![image](https://user-images.githubusercontent.com/15058114/38395982-755e1ece-38ea-11e8-9836-aa991677b54e.png)

![image](https://user-images.githubusercontent.com/15058114/38396017-b17acb6e-38ea-11e8-9e08-1c10c4fbfa57.png)

**Comment by sambuev** [comment]
Is UE4Druino have a support of 4.19? Is it still developing or abandoned?

**Comment by rizkyramadhan** [comment]
I got this message too! is there any workaround ?

**Comment by mpsaikiran** [comment]
packaging error with ue4duino

**Comment by mpsaikiran** [comment]
[ue4DuinoError.txt](https://github.com/RVillani/UE4Duino/files/2589032/ue4DuinoError.txt)

**Comment by RVillani** [comment]
@DarkenedGit Did you have the plugin with binaries for the UE4 version you were trying to use it on?

**Comment by RVillani** [comment]
@sambuev I'm not developing it, but I build the binaries for new UE4 versions when they are released. And if something breaks, I will fix it.

**Comment by RVillani** [comment]
@mpsaikiran It says it couldn't load one of the main libs. Are you trying to use it in a Blueprint-only project without the binaries?
