### ISSUE TITLE
UE4Duino_2.2.1_4.20 unable to open COM port. 

### ISSUE THREAD

**Issue by vidzrox** [RVillani/UE4Duino#5]
I am using UE4.20.3 version and I tried the exactly same steps that has uploaded in README.md file. 
I double checked the COM port and Baud rate, there is nothing wrong with that but it does not open the port!
When I tried the exactly same steps with UE4.16.3 is works perfectly!

**Comment by RVillani** [comment]
That was on me. Sorry!
I fixed that on version 2.2.3. But I recommend using the latest.

**Comment by RVillani** [comment]
I'm closing this since it was fixed. If the issue persists, you can open another one.
