### ISSUE TITLE
4.21 

### ISSUE THREAD

**Issue by paulmac00** [RVillani/UE4Duino#7]
Wow. What a gorgeous plug in. Worked on the first try (which is a huge rarity!). Well done. 

I have my master project in version 4.21, do you think you will have support for 4.21 anytime soon? 

Thanks again for an amazing plugin.

**Comment by RVillani** [comment]
I didn't know about that header!
I've included that instead of the bloated `windows.h` and some other style fixes in [release 2.2.5](https://github.com/RVillani/UE4Duino/releases/tag/2.2.5), with binaries for UE 4.24
